apiVersion: v1
kind: Namespace
metadata:
  name: certs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-certs
spec:
  capacity:
    storage: 1Gi
  accessModes: [ ReadOnlyMany ]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 100.106.1.47
    path: /fsds00Comun
  mountOptions: [ nfsvers=3, ro ]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-certs
  namespace: certs
spec:
  accessModes: [ ReadOnlyMany ]
  resources:
    requests: { storage: 1Gi }
  volumeName: pv-nfs-certs