apiVersion: v1
kind: Service
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/name: external-secrets-webhook
  ports:
    - name: https
      port: 443
      targetPort: 10250