apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-site1-cert
  namespace: site1
spec:
  secretStoreRef:
    name: k8s-cert-store
    kind: ClusterSecretStore
  target:
    name: tls-site1
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret_site1celmediafidelizacioncl
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: secret_site1celmediafidelizacioncl
        property: tls.key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-site2-cert
  namespace: site2
spec:
  secretStoreRef:
    name: k8s-cert-store
    kind: ClusterSecretStore
  target:
    name: tls-site2
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret_site2celmediafidelizacioncl
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: secret_site2celmediafidelizacioncl
        property: tls.key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-site3-cert
  namespace: site3
spec:
  secretStoreRef:
    name: k8s-cert-store
    kind: ClusterSecretStore
  target:
    name: tls-site3
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret_site3celmediafidelizacioncl
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: secret_site3celmediafidelizacioncl
        property: tls.key
