apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-site1-cert
  namespace: site1
spec:
  secretStoreRef: { name: certs-store, kind: ClusterSecretStore }
  target: { name: tls-site1, creationPolicy: Owner }
  data:
    - secretKey: tls.crt
      remoteRef: { key: secret_site1celmediafidelizacioncl, property: tls.crt }
    - secretKey: tls.key
      remoteRef: { key: secret_site1celmediafidelizacioncl, property: tls.key }
# Repetir para site2 y site3